version: "3.9"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-clubes
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SenhaForte@123"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - clubes-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-clubes
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ClubesDB;User Id=sa;Password=SenhaForte@123;TrustServerCertificate=True"
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - clubes-network

networks:
  clubes-network:

volumes:
  sql_data: